language: python
cache: pip
python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
script:
- if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then export CIBW_BUILD='cp27*'; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then export CIBW_BUILD='cp35*'; fi
- if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then export CIBW_BUILD='cp36*'; fi
- pip install cibuildwheel==0.10.1
- cibuildwheel --output-dir wheelhouse
deploy:
  provider: pypi
  user: SimLeek
  skip_existing: true
  password:
    secure: Iyg4UilFJrpZeOyRCdyVmUT76qZzkmtPGoundyjgKIjmXharVgdpN5G1v/7NRCjifxk9vnI5QGFUcd88LpnyTg5tbLm7gttiyV4cue/UPXc8LJEu1vhc3y6fjT26pr3slEFQNuhYWCEx1HxMilizDURqxOIrQeOnYAe8UBuYrwbs6lyVLE18ojetRpMeDJ9GDwOtYboizv3TtohR/sv/XbKMpqMVWFdQU8hhahi5KgdMYq2RF+em3L9xraUiVID5AZ6DqtCod5iHbULIoabguB2ykMFCBf5XEzs6vEw4dFpvK/aHG1Z6Mmc5sIm6+Cklq73lgqkKCCTRL5Vjq/lsPQ36J4RREO64+O6pQ052M9n+wXpEo8dvy2YDYE3TvlpOmbVJ5BJrExGgYgjsQ9hslp8GroU4aZbroljQuRz8SpzAXhiHnrB29IYNpkQQk93KZAIQdT7xY5iykhtU0eo/uk1vuB64qHWxxJ05PUqCBaaRwWPHOECKccc+fIH6aRIICeRjvyAo/LHDD8b+fC+HFR6nPHKswi7Mhzl9kFI58nbNR6kdQTSPrEiVdIiOTVTY1kBWIZweyV/vJGh+PUZyyWe61r5PFxU9lXMZH8oY/xvGPlhaUrgLvJ1tV24m1EGJ9dbbeuQ9T6dQYqY28IC7gl9JKbmnTBewQfW/F0T2N5I=
